
-- This is a list of all the source files in the smten-base package which must
-- be compiled with the Smten plugin to generate a corresponding
-- Smten.Compiled.* output.
import Smten.Prelude ()
import Smten.Control.Monad ()
import Smten.Data.Bool ()
import Smten.Data.Char ()
import Smten.Data.Function ()
import Smten.Data.Eq ()
import Smten.Data.EqInteger ()
import Smten.Data.List ()
import Smten.Data.Read ()
import Smten.Data.Ord ()
import Smten.Data.OrdInteger ()
import Smten.Data.Ordering ()
import Smten.Smten.Char ()
import Smten.Smten.Int ()
import Smten.Smten.List ()
import Smten.Smten.Tuple ()
import Smten.Smten.Unit ()
import Smten.System.IO_ ()
import Smten.Base.Control.Monad ()
import Smten.Base.Data.Either ()
import Smten.Base.Data.Functor ()
import Smten.Base.Data.List ()
import Smten.Base.Data.Maybe ()
import Smten.Base.Data.Tuple ()
import Smten.Base.GHC.Base ()
import Smten.Base.GHC.Char ()
import Smten.Base.GHC.Classes ()
import Smten.Base.GHC.Enum ()
import Smten.Base.GHC.List ()
import Smten.Base.GHC.Num ()
import Smten.Base.GHC.Real ()
import Smten.Base.GHC.Show ()
import Smten.Base.Prelude ()

main = error "smten-base.main"

